name: Publish Docker image
on:
  push:
    branches: [master]
jobs:
  push_to_registry:
    name: Push Docker image to private registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to private registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: registry.tomnieuw.land
          repository: tomnieuwland/gothbot
          tag_with_ref: true
